name: Add domain to blocked.txt

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain'
        required: true
        type: string

jobs:
  update_lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add domain to blocked.txt
        run: |
          tail -c1 domain_list/blocked.txt | read -r _ || echo >> domain_list/blocked.txt
          echo "${{ github.event.inputs.domain }}" >> domain_list/blocked.txt

      - name: Sort blocked.txt alphabetically
        run: |
          sort -u domain_list/blocked.txt -o domain_list/blocked.txt

      - name: Download external lists
        run: |
          curl -sSL https://github.com/itdoginfo/allow-domains/raw/main/Services/google_ai.lst -o google_ai.lst
          for f in *.lst; do
            sed -i 's/\r$//' "$f"
          done

      - name: Merge all lists and convert to comma-separated
        run: |
          cat google_ai.lst domain_list/blocked.txt | tr -d ' \t' | grep -v '^$' | sort -u | tr '\n' ',' | sed 's/,$//' > domain_list/blocked_v2rayng.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Added domain ${{ github.event.inputs.domain }} to blocked.txt"
          file_pattern: domain_list/blocked.txt domain_list/blocked_v2rayng.txt